# SITE CONFIG
title: AlunosMaio
description: Tudo em um sรณ lugar.
github_repository: raincorn/alunosmaio

#SITE SETTINGS
s_version: v0.0.1-rls+zeppelin.1
git_repo: true
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
